services:
  # CLI only service for building
  unify-cli:
    build:
      context: .
      dockerfile: docker/Dockerfile.cli
    volumes:
      - ./example:/workspace
    working_dir: /workspace
    command: unify build --source src --output dist
    profiles: [cli]

  # Development server with live reload
  unify-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "8080:8080"
    volumes:
      - ./example/src:/site
    profiles: [dev]

  # Production server with NGINX
  unify-nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - ./example/dist:/site
    profiles: [prod]

  # Apache production server
  unify-apache:
    build:
      context: .
      dockerfile: docker/Dockerfile.apache
    ports:
      - "8080:8080"
    volumes:
      - ./example/dist:/var/www/html:ro
    depends_on:
      - unify-cli
    profiles: [apache]