/**
 * `unify init blog` — a blog with a generator script (conformance-spec §19 /
 * SCF-03): `_scripts/gen-blog.mjs` reads `posts/*.md` and writes `blog.html`
 * and `feed.xml`, the sanctioned answer to collections and RSS (product-spec
 * §5). The scaffold ships `blog.html`/`feed.xml` already generated from the
 * two sample posts below — `unify init blog && unify build --dry-run
 * --strict` must exit 0 with no intervening step (SCF-04), so the listing
 * page and feed can't depend on the user having run the script first. The
 * script is there to regenerate both after adding or editing a post; its
 * checked-in output here is exactly what running it against `posts/`
 * produces (verified — see the implementation report).
 */
import { contactHtml, layoutHtml, navHtml, notFoundHtml, styleCss } from "./shared.js";

const SITE_NAME = "My Blog";

// Zero dependencies, ~50 lines of code (see the implementation report for why
// that runs a little past the spec's "~40 lines" estimate: it produces BOTH
// blog.html and feed.xml and escapes text into both HTML and XML correctly,
// which a 40-line version could only do by dropping one of those things).
const GEN_BLOG_MJS = `// Regenerates blog.html and feed.xml from posts/*.md. Zero dependencies.
// Run after adding or editing a post: node _scripts/gen-blog.mjs && unify build
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const POSTS = new URL("../posts/", import.meta.url);
const SITE_URL = "https://example.com";
const SITE_NAME = "My Blog";
const esc = (s = "") => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function readFrontmatter(text) {
  const m = text.match(/^---\\r?\\n([\\s\\S]*?)\\r?\\n---\\r?\\n?/);
  const data = {};
  for (const line of m ? m[1].split(/\\r?\\n/) : []) {
    const kv = line.match(/^(\\w+):\\s*(.*)$/);
    if (kv) data[kv[1]] = kv[2].trim();
  }
  return data;
}

const posts = readdirSync(POSTS)
  .filter((f) => f.endsWith(".md"))
  .map((file) => {
    const fm = readFrontmatter(readFileSync(new URL(file, POSTS), "utf8"));
    const slug = file.slice(0, -3);
    return { slug, title: fm.title || slug, date: fm.date || "", description: fm.description || "" };
  })
  .sort((a, b) => (a.date < b.date ? 1 : -1));

const items = posts
  .map(
    (p) =>
      '      <li><a href="/posts/' + p.slug + '.html">' + esc(p.title) + "</a> " +
      '<time datetime="' + p.date + '">' + p.date + "</time></li>",
  )
  .join("\\n");

writeFileSync(
  new URL("../blog.html", import.meta.url),
  "<!doctype html>\\n<html>\\n  <head>\\n    <title>Blog</title>\\n  </head>\\n  <body>\\n    <main>\\n" +
    "      <!-- generated by _scripts/gen-blog.mjs — do not edit by hand -->\\n      <h1>Blog</h1>\\n      <ul>\\n" +
    items + "\\n      </ul>\\n    </main>\\n  </body>\\n</html>\\n",
);

const rssItems = posts
  .map(
    (p) =>
      "    <item>\\n      <title>" + esc(p.title) + "</title>\\n      <link>" + SITE_URL + "/posts/" + p.slug +
      ".html</link>\\n      <description>" + esc(p.description) + "</description>\\n      <pubDate>" +
      new Date(p.date || Date.now()).toUTCString() + "</pubDate>\\n    </item>",
  )
  .join("\\n");

writeFileSync(
  new URL("../feed.xml", import.meta.url),
  '<?xml version="1.0" encoding="UTF-8"?>\\n<rss version="2.0"><channel>\\n    <title>' + esc(SITE_NAME) +
    "</title>\\n    <link>" + SITE_URL + "</link>\\n    <description>" + esc(SITE_NAME) + "</description>\\n" +
    rssItems + "\\n  </channel></rss>\\n",
);

console.log("gen-blog: wrote blog.html and feed.xml from " + posts.length + " post(s)");
`;

export const files = {
  "_layout.html": layoutHtml(SITE_NAME),

  "_includes/nav.html": navHtml([
    ["Home", "/"],
    ["Blog", "/blog.html"],
    ["Contact", "/contact.html"],
  ]),

  "_scripts/gen-blog.mjs": GEN_BLOG_MJS,

  "posts/hello-world.md": `---
title: Hello, world
date: 2026-01-15
description: The first post on this blog.
---

This is the first post. Edit or delete it, then add your own in \`posts/\`.

Run \`node _scripts/gen-blog.mjs\` after adding posts to regenerate \`blog.html\` and \`feed.xml\`.
`,

  "posts/shipping-in-public.md": `---
title: Shipping in public
date: 2026-02-03
description: Why this blog exists.
---

A second post, so the generator has more than one item to list.
`,

  "index.html": `<!doctype html>
<html>
  <head>
    <title>Home</title>
  </head>
  <body>
    <main>
      <h1>Welcome!</h1>
      <p>Read the <a href="/blog.html">blog</a>, or find out how to <a href="/contact.html">get in touch</a>.</p>
    </main>
  </body>
</html>
`,

  "contact.html": contactHtml(SITE_NAME),

  "404.html": notFoundHtml(),

  // Pre-generated — exactly what `node _scripts/gen-blog.mjs` produces from
  // the two posts above, so the scaffold builds clean with no extra step.
  "blog.html": `<!doctype html>
<html>
  <head>
    <title>Blog</title>
  </head>
  <body>
    <main>
      <!-- generated by _scripts/gen-blog.mjs — do not edit by hand -->
      <h1>Blog</h1>
      <ul>
      <li><a href="/posts/shipping-in-public.html">Shipping in public</a> <time datetime="2026-02-03">2026-02-03</time></li>
      <li><a href="/posts/hello-world.html">Hello, world</a> <time datetime="2026-01-15">2026-01-15</time></li>
      </ul>
    </main>
  </body>
</html>
`,

  "feed.xml": `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel>
    <title>My Blog</title>
    <link>https://example.com</link>
    <description>My Blog</description>
    <item>
      <title>Shipping in public</title>
      <link>https://example.com/posts/shipping-in-public.html</link>
      <description>Why this blog exists.</description>
      <pubDate>Tue, 03 Feb 2026 00:00:00 GMT</pubDate>
    </item>
    <item>
      <title>Hello, world</title>
      <link>https://example.com/posts/hello-world.html</link>
      <description>The first post on this blog.</description>
      <pubDate>Thu, 15 Jan 2026 00:00:00 GMT</pubDate>
    </item>
  </channel></rss>
`,

  "assets/style.css": styleCss(),
};
