/**
 * `unify init blog` — a blog with the generator seam worked end-to-end
 * (conformance-spec §19 / SCF-03, SCF-05): `_scripts/gen.mjs` reads
 * `posts/*.md` and `_data/authors.json` and writes `blog.html` and
 * `feed.xml`, the sanctioned answer to collections and RSS (product-spec
 * §5). Two ratification findings shaped this scaffold, and both are
 * load-bearing (docs/ratification.md §6; _notes/ratification-rounds-7-20.md,
 * rounds 16/19/20):
 *
 * - Twelve of twelve agents across rounds 19-20 wrote a generator script
 *   unprompted — it is the most universal thing anyone builds on top of
 *   unify — and round 16 showed the scaffold teaches shapes the prose
 *   failed at (5/5 on the named-slot fill) and mis-teaches placeholders
 *   just as efficiently (3/4 copied one verbatim). What this file
 *   demonstrates, agents will copy; so it demonstrates the pattern
 *   properly: the run-it-yourself contract (`node _scripts/gen.mjs &&
 *   unify build` — the authoring rules' own literal, and the two must
 *   agree), a generated-file marker, and the derived files shipped
 *   pre-generated.
 * - Eight of those twelve correctly excluded their data file and still
 *   published its private fields. File-level exclusion cannot protect a
 *   field, and no diagnostic can exist once a script copies one into a
 *   page — that page is ordinary content. The only enforcement point is
 *   the generator itself, so gen.mjs names the fields it emits — never
 *   spreads the record — and its comments say why.
 *
 * The scaffold ships `blog.html`/`feed.xml` already generated from the two
 * sample posts and the authors file below — `unify init blog && unify build
 * --dry-run --strict` must exit 0 with no intervening step (SCF-04), so the
 * listing page and feed can't depend on the user having run the script
 * first. The checked-in copies are byte-identical to what running the
 * script produces: the SCF-03 test deletes them, reruns the script, and
 * compares the whole tree.
 */
import { contactHtml, layoutHtml, navHtml, notFoundHtml, styleCss } from "./shared.js";

const SITE_NAME = "My Blog";

// Zero dependencies, ~70 lines: it produces BOTH blog.html and feed.xml,
// escapes text into HTML and XML correctly, and carries the field-privacy
// comments SCF-05 requires — the teaching is the point, not the byte count.
const GEN_MJS = `// Regenerates blog.html and feed.xml — the derived files — from posts/*.md
// and _data/authors.json. Zero dependencies, run it yourself:
//   node _scripts/gen.mjs && unify build
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const POSTS = new URL("../posts/", import.meta.url);
const SITE_URL = "https://example.com";
const SITE_NAME = "My Blog";
const MARKER = "generated by _scripts/gen.mjs — edit the data, not this file";
const esc = (s = "") => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// _data/authors.json holds a private field (email) beside the public ones.
// The underscore keeps the FILE out of the built site; only this script can
// keep a FIELD out of the pages it writes.
const AUTHORS = JSON.parse(readFileSync(new URL("../_data/authors.json", import.meta.url), "utf8"));

function readFrontmatter(text) {
  const m = text.match(/^---\\r?\\n([\\s\\S]*?)\\r?\\n---\\r?\\n?/);
  const data = {};
  for (const line of m ? m[1].split(/\\r?\\n/) : []) {
    const kv = line.match(/^(\\w+):\\s*(.*)$/);
    if (kv) data[kv[1]] = kv[2].trim();
  }
  return data;
}

const posts = readdirSync(POSTS)
  .filter((f) => f.endsWith(".md"))
  .map((file) => {
    const fm = readFrontmatter(readFileSync(new URL(file, POSTS), "utf8"));
    const slug = file.slice(0, -3);
    // Name the fields you emit — never spread the record (no {...author}).
    // Picking \`name\` and \`url\` is what keeps \`email\` private: it never
    // leaves this file, and no build check could catch it if it did.
    const { name = "", url = "" } = AUTHORS[fm.author] || {};
    return { slug, title: fm.title || slug, date: fm.date || "", description: fm.description || "", author: { name, url } };
  })
  .sort((a, b) => (a.date < b.date ? 1 : -1));

const items = posts
  .map((p) => {
    const by = p.author.name
      ? ' by <a href="' + p.author.url + '" rel="author">' + esc(p.author.name) + "</a>"
      : "";
    return '      <li><a href="/posts/' + p.slug + '.html">' + esc(p.title) + "</a> " +
      '<time datetime="' + p.date + '">' + p.date + "</time>" + by + "</li>";
  })
  .join("\\n");

writeFileSync(
  new URL("../blog.html", import.meta.url),
  "<!doctype html>\\n<html>\\n  <head>\\n    <title>Blog</title>\\n  </head>\\n  <body>\\n    <main>\\n" +
    "      <!-- " + MARKER + " -->\\n      <h1>Blog</h1>\\n      <ul>\\n" +
    items + "\\n      </ul>\\n    </main>\\n  </body>\\n</html>\\n",
);

// RSS's <author> element wants an email address — exactly the field that
// stays private — so the feed carries no author at all.
const rssItems = posts
  .map(
    (p) =>
      "    <item>\\n      <title>" + esc(p.title) + "</title>\\n      <link>" + SITE_URL + "/posts/" + p.slug +
      ".html</link>\\n      <description>" + esc(p.description) + "</description>\\n      <pubDate>" +
      new Date(p.date || Date.now()).toUTCString() + "</pubDate>\\n    </item>",
  )
  .join("\\n");

writeFileSync(
  new URL("../feed.xml", import.meta.url),
  '<?xml version="1.0" encoding="UTF-8"?>\\n<!-- ' + MARKER + ' -->\\n<rss version="2.0"><channel>\\n    <title>' + esc(SITE_NAME) +
    "</title>\\n    <link>" + SITE_URL + "</link>\\n    <description>" + esc(SITE_NAME) + "</description>\\n" +
    rssItems + "\\n  </channel></rss>\\n",
);

console.log("gen.mjs: wrote blog.html and feed.xml from " + posts.length + " post(s)");
`;

export const files = {
  "_layout.html": layoutHtml(SITE_NAME),

  "_includes/nav.html": navHtml([
    ["Home", "/"],
    ["Blog", "/blog.html"],
    ["Contact", "/contact.html"],
  ]),

  // The record every generator grows eventually: public fields beside one
  // that must never ship. It lives under `_data/` (excluded, like all `_*`),
  // and only gen.mjs decides which fields leave it.
  //
  // The author's `url` is an EXTERNAL personal site on the reserved `.example`
  // TLD (RFC 2606), deliberately not a path under this site's own domain. It
  // read `https://example.com/sam` until the sitemap work made `--base-url`
  // the flag every site sets: `--base-url https://example.com/` then makes
  // that link internal (REF-02 strips the matching origin), it resolves to a
  // page no template ships, and the scaffold fails its own golden path with a
  // broken-reference problem. A placeholder that collides with the most
  // obvious value a reader will type is a scaffold defect, not a CLI one.
  "_data/authors.json": `{
  "sam": {
    "name": "Sam Rivera",
    "url": "https://sam.example/",
    "email": "sam@example.com"
  }
}
`,

  "_scripts/gen.mjs": GEN_MJS,

  "posts/hello-world.md": `---
title: Hello, world
date: 2026-01-15
author: sam
description: The first post on this blog.
---

This is the first post. Edit or delete it, then add your own in \`posts/\`.

Run \`node _scripts/gen.mjs\` after adding a post or editing \`_data/authors.json\` to regenerate \`blog.html\` and \`feed.xml\`.
`,

  "posts/shipping-in-public.md": `---
title: Shipping in public
date: 2026-02-03
author: sam
description: Why this blog exists.
---

A second post, so the generator has more than one item to list.
`,

  "index.html": `<!doctype html>
<html>
  <head>
    <title>Home</title>
  </head>
  <body>
    <main>
      <h1>Welcome!</h1>
      <p>Read the <a href="/blog.html">blog</a>, or find out how to <a href="/contact.html">get in touch</a>.</p>
    </main>
  </body>
</html>
`,

  "contact.html": contactHtml(SITE_NAME),

  "404.html": notFoundHtml(),

  // Pre-generated — exactly what `node _scripts/gen.mjs` produces from the
  // two posts and the authors file above, so the scaffold builds clean with
  // no extra step. Note the byline: the author's public name and url, never
  // the email.
  "blog.html": `<!doctype html>
<html>
  <head>
    <title>Blog</title>
  </head>
  <body>
    <main>
      <!-- generated by _scripts/gen.mjs — edit the data, not this file -->
      <h1>Blog</h1>
      <ul>
      <li><a href="/posts/shipping-in-public.html">Shipping in public</a> <time datetime="2026-02-03">2026-02-03</time> by <a href="https://sam.example/" rel="author">Sam Rivera</a></li>
      <li><a href="/posts/hello-world.html">Hello, world</a> <time datetime="2026-01-15">2026-01-15</time> by <a href="https://sam.example/" rel="author">Sam Rivera</a></li>
      </ul>
    </main>
  </body>
</html>
`,

  "feed.xml": `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by _scripts/gen.mjs — edit the data, not this file -->
<rss version="2.0"><channel>
    <title>My Blog</title>
    <link>https://example.com</link>
    <description>My Blog</description>
    <item>
      <title>Shipping in public</title>
      <link>https://example.com/posts/shipping-in-public.html</link>
      <description>Why this blog exists.</description>
      <pubDate>Tue, 03 Feb 2026 00:00:00 GMT</pubDate>
    </item>
    <item>
      <title>Hello, world</title>
      <link>https://example.com/posts/hello-world.html</link>
      <description>The first post on this blog.</description>
      <pubDate>Thu, 15 Jan 2026 00:00:00 GMT</pubDate>
    </item>
  </channel></rss>
`,

  "assets/style.css": styleCss(),
};
