/**
 * The template registry — `unify init [template]` (conformance-spec §19).
 *
 * A built-in template IS a directory of this repository: `templates/<name>/`,
 * a complete project laid out as `init` lays one out (§19.4) — `site/` beside
 * `AGENTS.md`, `DEPLOY.md`, `unify.yaml`, the blog's `scripts/gen.mjs` — and
 * usable as a git template on its own (§19.9:
 * `unify init https://github.com/fwdslsh/unify/templates/blog`). The name is a
 * shortcut to that directory, with one difference: it needs no network and no
 * git, because the directory is embedded here as data.
 *
 * `./snapshot.js` is that embedding, GENERATED by scripts/sync-templates.mjs
 * and checked in; tests/unit/templates.test.js fails when it and
 * `templates/` disagree. It is reached by an ordinary static `import` chain
 * rooted at src/cli.js, which is what "compiled into the binary" means in
 * practice: `bun build --compile` bundles by tracing imports, not by reading
 * the filesystem at run time, and a compiled single-file executable has no
 * sibling directory to read — so nothing under this directory does
 * `fs.readFileSync(new URL(..., import.meta.url))` or any other filesystem
 * lookup relative to its own module location (§19.5). A text file is a
 * string in the snapshot; the one binary (the share image) is base64,
 * decoded here to the `Uint8Array` `init` writes verbatim.
 */
import { SNAPSHOT } from "./snapshot.js";

/**
 * @param {Record<string, string|{base64: string}>} map
 * @returns {Record<string, string|Uint8Array>}
 */
function decode(map) {
  return Object.fromEntries(
    Object.entries(map).map(([path, value]) => [path, typeof value === "string" ? value : new Uint8Array(Buffer.from(value.base64, "base64"))]),
  );
}

/**
 * @type {Record<string, Record<string, string|Uint8Array>>}
 * Source-root-relative path → content, per template. Key order is the order
 * `unify --help`-style listings offer them in.
 */
export const TEMPLATES = Object.fromEntries(
  ["default", "basic", "blog", "docs", "portfolio"].map((name) => [name, decode(SNAPSHOT[name].files)]),
);

/**
 * §19.4/§19.6/§19.8 — what each template keeps at the PROJECT ROOT, beside the
 * source tree: AGENTS.md, DEPLOY.md and unify.yaml for every template, plus
 * build material that is not content (the blog's generator in `scripts/`).
 * Keys are project-root-relative.
 * @type {Record<string, Record<string, string|Uint8Array>>}
 */
export const TEMPLATE_ROOT_FILES = Object.fromEntries(
  Object.keys(TEMPLATES).map((name) => [name, decode(SNAPSHOT[name].rootFiles)]),
);
