// Writes blog.html and feed.xml — the derived files — from the site's posts/*.md
// and _data/authors.json. Both start out as examples (site/_examples/post.md,
// site/_examples/authors.json): copy them into place and the next build lists
// the post. unify runs this file itself before every build, dev
// rebuild and audit, because unify.yaml names it:
//   generate: scripts/gen.mjs
// so a plain `unify build` is the whole command. unify hands it three paths
// (conformance-spec §33.2): argv[2] the source root, argv[3] a fresh overlay
// directory whose files join the build as ordinary pages, argv[4] a snapshot of
// the build's settings. Nothing here is written into site/: the overlay is
// thrown away after the build, so there is no generated file to keep fresh,
// commit, or edit by mistake. It lives in scripts/ beside the site, not inside
// it, because build tooling is not content. To look at its output on its own:
//   node scripts/gen.mjs site some-empty-dir
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [, , sourceRoot, outDir, contextPath] = process.argv;
if (!sourceRoot || !outDir) {
  throw new Error("gen.mjs: unify runs this (generate: scripts/gen.mjs in unify.yaml); by hand, pass the site and an output directory");
}
const POSTS = join(sourceRoot, "posts");
const SITE_NAME = "My Blog";
const LISTING_DESCRIPTION =
  `Every post on ${SITE_NAME}, newest first — a listing page written by scripts/gen.mjs, never by hand.`;
// A feed's links have to be absolute, so they take the address you build with
// (`unify build --base-url https://you.example/`, see DEPLOY.md), read from the
// settings snapshot. Without a --base-url there is no real address yet, and the
// placeholder below is what the feed advertises — `you.example` is reserved and
// never resolves, which is the point.
const context = contextPath ? JSON.parse(readFileSync(contextPath, "utf8")) : null;
const SITE_URL = (context?.site?.baseUrl ?? "https://you.example/").replace(/\/$/, "");
const MARKER = "generated by scripts/gen.mjs — edit the data, not this file";

// Text content, then attribute values. Both, because a post title with an
// ampersand in it belongs in this page as text and in that page's link as
// an attribute, and one escaper cannot be right for both.
const esc = (s = "") => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escAttr = (s = "") => esc(s).replace(/"/g, "&quot;");
const cmp = (x, y) => (x < y ? -1 : x > y ? 1 : 0);

// _data/authors.json holds a private field (email) beside the public ones.
// The underscore keeps the FILE out of the built site; only this script can
// keep a FIELD out of the pages it writes. A fresh scaffold has no copy yet
// (site/_examples/authors.json is the one to copy), so none means no authors.
const authorsPath = join(sourceRoot, "_data", "authors.json");
const AUTHORS = existsSync(authorsPath) ? JSON.parse(readFileSync(authorsPath, "utf8")) : [];

function readFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  const data = {};
  for (const line of m ? m[1].split(/\r?\n/) : []) {
    const kv = line.match(/^([\w:-]+):\s*(.*)$/);
    // A quoted YAML scalar keeps its quotes in a reader this naive; drop
    // them, or a title with a colon in it lands in the listing wearing them.
    if (kv) data[kv[1]] = kv[2].trim().replace(/^"([\s\S]*)"$/, "$1");
  }
  return data;
}

// No posts/ yet is a scaffold nobody has written in: an empty listing, not an error.
const posts = (existsSync(POSTS) ? readdirSync(POSTS) : [])
  .filter((f) => f.endsWith(".md"))
  .map((file) => {
    const fm = readFrontmatter(readFileSync(join(POSTS, file), "utf8"));
    const slug = file.slice(0, -3);
    // Name the fields you emit — never spread the record (no {...author}).
    // Picking `name` and `url` is what keeps `email` private: it never
    // leaves this file, and no build check could catch it if it did.
    const record = AUTHORS.find((a) => a.name === fm.author) || {};
    const author = { name: record.name || "", url: record.url || "" };
    return { slug, title: fm.title || slug, date: fm.date || "", description: fm.description || "", author };
  })
  // Newest first, ties broken by filename, so two runs always agree.
  .sort((a, b) => cmp(b.date, a.date) || cmp(a.slug, b.slug));

const listing = posts.length === 0
  ? "      <p>No posts yet. Copy <code>site/_examples/post.md</code> into <code>site/posts/</code> to write the first.</p>"
  : "      <ul>\n" + posts.map((p) => {
    // <time> splits the machine's value from the reader's: the attribute keeps
    // the full instant a feed needs, the text shows the day. The slice is the
    // whole formatting rule on purpose — no locale, no month names, nothing
    // invented from a value the author did not write.
    const when = p.date
      ? ' <time datetime="' + escAttr(p.date) + '">' + esc(p.date.slice(0, 10)) + "</time>"
      : "";
    const by = p.author.name
      ? ' by <a href="' + escAttr(p.author.url) + '" rel="author">' + esc(p.author.name) + "</a>"
      : "";
    return '        <li><a href="/posts/' + p.slug + '.html">' + esc(p.title) + "</a>" + when + by + "</li>";
  }).join("\n") + "\n      </ul>";

mkdirSync(outDir, { recursive: true });

// The listing page. It is a page like any other once it is in the overlay:
// the layout wraps it, its head merges, and every link in it is checked.
writeFileSync(
  join(outDir, "blog.html"),
  "<!doctype html>\n<html>\n  <head>\n    <title>Blog</title>\n" +
    '    <meta name="description" content="' + escAttr(LISTING_DESCRIPTION) + '">\n' +
    '    <meta property="og:title" content="Blog">\n' +
    '    <meta property="og:description" content="' + escAttr(LISTING_DESCRIPTION) + '">\n' +
    '    <link rel="alternate" type="application/rss+xml" title="' + escAttr(SITE_NAME) + '" href="/feed.xml">\n' +
    "  </head>\n  <body>\n    <main>\n" +
    "      <!-- " + MARKER + " -->\n" +
    "      <h1>Blog</h1>\n" +
    listing + "\n" +
    '      <p>Every post above, in one file: the <a href="/feed.xml">RSS feed</a>.</p>\n' +
    "    </main>\n  </body>\n</html>\n",
);

// RSS's <author> element wants an email address — exactly the field that
// stays private — so the feed carries no author at all. A post with no
// usable date gets no <pubDate> either: leave it out rather than invent one.
// (unify can write an Atom feed.xml itself from the posts' schema: BlogPosting
// once you build with --base-url; a feed.xml of your own, like this one, always
// wins and switches that off. Delete this half to use unify's.)
const rssItems = posts
  .map((p) => {
    const at = p.date ? new Date(p.date) : null;
    const pubDate =
      at && !Number.isNaN(at.getTime()) ? "      <pubDate>" + at.toUTCString() + "</pubDate>\n" : "";
    return "    <item>\n" +
      "      <title>" + esc(p.title) + "</title>\n" +
      "      <link>" + SITE_URL + "/posts/" + p.slug + ".html</link>\n" +
      "      <description>" + esc(p.description) + "</description>\n" +
      pubDate +
      "    </item>";
  })
  .join("\n");

writeFileSync(
  join(outDir, "feed.xml"),
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
    "<!-- " + MARKER + " -->\n" +
    '<rss version="2.0">\n  <channel>\n' +
    "    <title>" + esc(SITE_NAME) + "</title>\n" +
    "    <link>" + SITE_URL + "/blog.html</link>\n" +
    "    <description>" + esc(LISTING_DESCRIPTION) + "</description>\n" +
    rssItems +
    "\n  </channel>\n</rss>\n",
);

console.log("gen.mjs: wrote blog.html and feed.xml from " + posts.length + " post(s)");
