// Writes blog.html — the post listing — from the posts unify has already read.
// unify runs this file itself before every build, dev rebuild and audit,
// because unify.yaml names it:
//   generate: scripts/gen.mjs
// so a plain `unify build` is the whole command. unify hands it three paths
// (conformance-spec §33.2): argv[2] the source root, argv[3] a fresh overlay
// directory whose files join the build as ordinary pages, argv[4] a snapshot
// of the build's settings, generator-context.json. That snapshot names
// source-pages.json (§33.7): every source page's authored title, description,
// date and <meta> records, read by unify's own frontmatter reader — so this
// script parses no frontmatter, and a post with a broken front block is
// reported by unify, located, before this script ever runs.
// Nothing here is written into site/: the overlay is thrown away after the
// build, so there is no generated file to keep fresh, commit, or edit by
// mistake. It lives in scripts/ beside the site, not inside it, because
// build tooling is not content.
//
// The feed is not this script's job. Build with --base-url (see DEPLOY.md) and
// unify writes feed.xml itself: an Atom feed of every page declaring
// schema: BlogPosting, which the example post does, with sitemap.xml beside it.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [, , sourceRoot, outDir, contextPath] = process.argv;
if (!sourceRoot || !outDir || !contextPath) {
  throw new Error("gen.mjs: unify runs this (generate: scripts/gen.mjs in unify.yaml) and hands it the source page list; run unify build to see its output");
}
const context = JSON.parse(readFileSync(contextPath, "utf8"));
if (!context.inputs?.sourcePages) {
  throw new Error("gen.mjs: the source page list is switched off; remove source-inventory: false from unify.yaml (it is on whenever generate: is set)");
}
const inventory = JSON.parse(readFileSync(context.inputs.sourcePages, "utf8"));

const SITE_NAME = "My Blog";
const LISTING_DESCRIPTION =
  `Every post on ${SITE_NAME}, newest first — a listing page written by scripts/gen.mjs, never by hand.`;
const MARKER = "generated by scripts/gen.mjs — edit the data, not this file";

// Text content, then attribute values. Both, because a post title with an
// ampersand in it belongs in this page as text and in that page's link as
// an attribute, and one escaper cannot be right for both.
const esc = (s = "") => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escAttr = (s = "") => esc(s).replace(/"/g, "&quot;");
const cmp = (x, y) => (x < y ? -1 : x > y ? 1 : 0);

// _data/authors.json holds a private field (email) beside the public ones.
// The underscore keeps the FILE out of the built site; only this script can
// keep a FIELD out of the pages it writes. A fresh scaffold has no copy yet
// (site/_examples/authors.json is the one to copy), so none means no authors.
const authorsPath = join(sourceRoot, "_data", "authors.json");
const AUTHORS = existsSync(authorsPath) ? JSON.parse(readFileSync(authorsPath, "utf8")) : [];

// A post is a source page under posts/. Its title and date are the frontmatter's,
// as unify read them; `author` is the one <meta> that frontmatter synthesizes.
// No posts/ yet is a scaffold nobody has written in: an empty listing, not an error.
const posts = inventory.pages
  .filter((p) => p.source.startsWith("posts/"))
  .map((p) => {
    // Name the fields you emit — never spread the record (no {...author}).
    // Picking `name` and `url` is what keeps `email` private: it never
    // leaves this file, and no build check could catch it if it did.
    const byline = p.meta.find((m) => m.name === "author")?.content?.trim() ?? "";
    const record = AUTHORS.find((a) => a.name === byline) || {};
    const author = { name: record.name || "", url: record.url || "" };
    return { href: p.href, title: p.title || p.source, date: p.date || "", author };
  })
  // Newest first, ties broken by address, so two runs always agree.
  .sort((a, b) => cmp(b.date, a.date) || cmp(a.href, b.href));

const listing = posts.length === 0
  ? "      <p>No posts yet. Copy <code>site/_examples/post.md</code> into <code>site/posts/</code> to write the first.</p>"
  : "      <ul>\n" + posts.map((p) => {
    // <time> splits the machine's value from the reader's: the attribute keeps
    // the full instant, the text shows the day. The slice is the whole
    // formatting rule on purpose — no locale, no month names, nothing
    // invented from a value the author did not write.
    const when = p.date
      ? ' <time datetime="' + escAttr(p.date) + '">' + esc(p.date.slice(0, 10)) + "</time>"
      : "";
    const by = p.author.name
      ? ' by <a href="' + escAttr(p.author.url) + '" rel="author">' + esc(p.author.name) + "</a>"
      : "";
    return '        <li><a href="' + escAttr(p.href) + '">' + esc(p.title) + "</a>" + when + by + "</li>";
  }).join("\n") + "\n      </ul>";

mkdirSync(outDir, { recursive: true });

// The listing page. It is a page like any other once it is in the overlay:
// the layout wraps it, its head merges, and every link in it is checked.
writeFileSync(
  join(outDir, "blog.html"),
  "<!doctype html>\n<html>\n  <head>\n    <title>Blog</title>\n" +
    '    <meta name="description" content="' + escAttr(LISTING_DESCRIPTION) + '">\n' +
    '    <meta property="og:title" content="Blog">\n' +
    '    <meta property="og:description" content="' + escAttr(LISTING_DESCRIPTION) + '">\n' +
    "  </head>\n  <body>\n    <main>\n" +
    "      <!-- " + MARKER + " -->\n" +
    "      <h1>Blog</h1>\n" +
    listing + "\n" +
    "    </main>\n  </body>\n</html>\n",
);

console.log("gen.mjs: wrote blog.html from " + posts.length + " post(s)");
