name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run tests
        run: bun test        
        
      - name: Build executable
        run: bun build --compile --outfile unify bin/cli.js --minify
        
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: unify-executable
          path: unify
          retention-days: 30

      - name: Setup Node.js for NPM publishing
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
           
      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                
